<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BatikCategory;

class BatikCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $lists = [
            ['Batik Bali', 'Industri batik Bali dimulai sekitar tahun 1970 yang dipelopori antara lain oleh Pande Ketut Krisna yang berasal dari Banjar Tegeha, Desa Batubulan, Sukawati Gianyar, Bali. Pada awalnya, Ketut Krisna masih menggunakan teknik batik cap dengan bantuan alat tenun yang manual atau biasa disebut dengan Alat Tenun Bukan Mesin. Masyarakat Bali sendiri sebenarnya menggunakan kain batik dalam berbagai aktivitas yang erat kaitannya dengan upacara adat ataupun ritual keagamaan yaitu kain batik yang diikatkan pada bagian pinggang juga dijadikan sebagai ikat kepala atau dalam bahasa bali diistilahkan dengan udeng.'],
            ['Batik Betawi', 'Suku Betawi - penduduk asli Batavia, mempunyai karakter kebudayaan yang fleksibel sehingga produk kebudayaan yang dilahirkan menjadi unik. Hal tersebut tidak lepas dari adanya pengaruh bangsa-bangsa luar. Salah satu hasil produk dari penyatuan berbagai budaya tersebut adalah Batik Betawi. Karena permintaan pasar akan batik mengalami kenaikan yang pesat, maka pengusaha batik yang pada masa itu mayoritas adalah pengusaha Tionghoa, mendatangkan perajin batik dari Pekalongan dan Solo untuk mengerjakannya di Batavia, yaitu di daerah Karet. Filosofi atau makna dari batik betawi adalah sebagai keseimbangan alam semesta untuk memenuhi hidup yang sejahtera dan berkah. Batik Betawi berbentuk kain panjang dan kain sarung yang motifnya dikerjakan dengan tulis dan cap. Bahan kainnya berupa sutera, ATBM, prima, primis dan dobi.'],
            ['Batik Celup', 'Batik Celup sebenarnya adalah teknik pembuatan batik, teknik ini adalah teknik mewarnai kain dengan mengikat kain dengan cara tertentu sebelum dilakukan pencelupan. Menurut sejarah, teknik celup ikat berasal dari Tiongkok, teknik ini kemudian berkembang sampai ke India dan wilayah-wilayah nusantara. Teknik celup ikat diperkenalkan ke nusantara oleh orang-orang India melalui misi perdagangan teknik ini mendapat perhatian besar terutama karena keindahan ragam hiasnya dalam rangkaian warna warni yang menawan. Penggunaan teknik celup ikat ini antara lain di Sumatra, khususnya Palembang, di Kalimantan Selatan, Jawa dan Bali. Dalam proses pewarnaan batik celup, jaman dahulu zat pewarna yang digunakan berasal dari alam. Namun dengan berkembangnya ilmu pengetahuan dan teknologi zat pewarna alami mulai ditinggalkan hal ini terjadi terutama karena pewarna sintetis memiliki jumlah warna yang hampir tak terbatas, disamping itu juga, proses pewarnaan alam juga lebih rumit pewarna sintetis. Meskipun demikian, keduanya memiliki keunggulan masing-masing.'],
            ['Batik Cendrawasih', 'Bekembangnya Budaya dan teknologi membatik di Papua sendiri bermula saat Indonesia mendapatkan bantuan dari the United Nation Development Programme ( UNDP ) pada tahun 1985. Batuan yang dimaksud yaitu berupa pemberdayaan kebudayaan di daerah Indonesia bagian timur yakni Papua. Untuk memberikan pelatihan membatik di papua pemerintah kala itu mendatangkan pelatih batik dari Jawa khususnya dari Kota Yogyakarta. Setelah mendapatkan pelatihan membatik, para pengrajin batik dari Papua lama – kelamaan mulai terbiasa membatik bahkan menghasilkan batik khas mereka sendiri. Salah satunya yaitu batik cendrawasih ini.'],
            ['Batik Ceplok', 'Batik ceplok atau ceplokan merupakan jenis batik yang memiliki pola atau motif dengan bentuk dasar geometri, seperti persegi, oval maupun bintang yang disusun melingkar sehingga menyerupai sekuntum bunga dengan pola simetris. Bentuk tersebut terinspirasi dari buah aren yang dibelah empat. Variasi dalam batik ceplok sangat kaya, bentuk utama geometris bisa diisi atau dalam istilah batik disebut isen-isen dengan motif batik lainya seperti kawung, parang klithik, truntum atau hiasan isen-isen lainnya seperti bunga dan gerdo atau garuda. Motif batik ceplok ini menggambarkan suratan takdir dan keteraturan kehidupan, bawah dalam kehidupan di dunia sudah ada aturan dan garisnya. Sehingga diharapkan si pemakai batik ini dapat menjalani hidup secara teratur. Pada zaman dulu, batik ceplok digunakan oleh aparat pemerintahan. Dengan menggunakan motif batik ini diharapkan para aparat pemerintahan akan bertugas dengan benar dan jujur.'],
            ['Batik Ciamis', 'Kesahajaan merupakan ciri khas batik ciamis. Warna hitam, putih, dipadu coklat kekuningan, begitu menonjol pada motif batik daerah ini. Ragam hias batik ciamisan bernuansa naturalistik, banyak menggambarkan flora dan fauna serta lingkungan alam sekitar. Kesederhanaan corak batik ciamis tak lepas dari sejarah keberadaannya yang banyak dipengaruhi daerah lain, seperti ragam hias pesisiran dari Indramayu dan Cirebon. Selain itu, pengaruh batik non pesisir, seperti dari Solo dan Yogyakarta, tak kalah dominan. Pengaruh dari wilayah pesisir dan non pesisir yang berpadu dengan nilai-nilai budaya Sunda dan kehidupan sosial sehari-hari masyarakat Ciamis melahirkan ragam motif batik ciamisan yang sesuai dengan gaya dan selera masyarakat setempat, bersahaja tetapi elegan. Alhasil, corak batik ciamisan tidak memiliki makna filosofi, perlambang, nilai sakral, atau menunjukkan status sosial tertentu. Penciptaan motif atau ragam hias batiknya lebih ditekankan pada ungkapan kesederhanaan untuk memenuhi kebutuhan sandang masyarakat. Kesederhanaan itu tertuang dalam bentuk-bentuk yang terinspirasi dari alam sekitar dan kejadian sehari-hari.'],
            ['Batik Garutan', 'Batik garutan umumnya digunakan untuk kain sinjang, namun berfungsi juga untuk memenuhi kebutuhan sandang dan lainnya. Bentuk motif batik Garut merupakan cerminan dari kehidupan sosial budaya, falsafah hidup, dan adat istiadat orang Sunda. Motif-motif batik Garut dihadirkan berbentuk geometrik sebagai ciri khas ragam hiasnya, selain itu bermotif flora dan fauna. Bentuk geometri umumnya mengarah ke garis diagonal dan bentuk kawung atau belah ketupat. Warnanya didominasi oleh warna krem dipadukan dengan warna-warna cerah lainnya yang merupakan karakteristik khas batik garutan. Saat ini pengolahan batik garutan terkonsentrasi di Garut kota.'],
            ['Batik Gentongan', 'Batik Gentongan, primadona dari batik Madura. Disebut gentongan karena proses pembuatannya melalui proses perendaman warna dalam gentong. Pengrajin batik akan mencelup-celupkan kain batik yang telah digambar kedalam gentong dan mendiamkannya selama 24 jam,lalu mengulang mencelup-celupkannya lagi. Hal ini dilakukan selama enam bulan sampai satu tahun. Batik Gentongan tak ubahnya seperti batik-batik lain di Indonesia yang harus menghadapi kemajuan global sehingga harus selalu dilakukan inovasi dan pembaruan. Di Madura, kampung halaman Batik Gentongan, perjuangan untuk mempertahankan eksistensi batik khas Madura ini memang lebih sulit daripada batik-batik lain dari wilayah Jawa misalnya. Di Madura, kini hanya tersisa dua orang pegiat batik yang masih melestarikan Batik Gentongan.'],
            ['Batik Kawung', 'Batik Kawung adalah motif batik yang bentuknya berupa bulatan mirip buah kawung (sejenis kelapa atau kadang juga dianggap sebagai aren atau kolang-kaling) yang ditata rapi secara geometris. Kadang, motif ini juga ditafsirkan sebagai gambar bunga lotus (teratai) dengan empat lembar mahkota bunga yang merekah. Lotus adalah bunga yang melambangkan umur panjang dan kesucian. Maka dari itu makna filosofi dari motif kawung itu sangat dalam yaitu, kesempurnaan, kesucian, kemurnian, serta polanya yang geometris, diharapkan dapat memberikan manfaat bagi orang lain pada setiap tingkah lakunya.'],
            ['Batik Keraton', 'Batik keraton adalah jenis batik yang dikembangkan dan digunakan di lingkungan keraton. Motif dan penggunaannya diatur dengan norma-norma kraton. Karena setiap corak menunjukkan status pemakainya, corak motif batik keraton disebut motif larangan. Hal ini disebabkan pada awalnya motif-motif tertentu dilarang dikenakan oleh masyarakat umum, kecuali oleh kerabat keraton. Dalam masyarakat keraton jawa, membatik dianggap sebagai kegiatan pengabdian kepada raja. Batik tradisional di lingkungan Kasultanan Yogyakarta mempunyai ciri khas dalam tampilan warna dasar putih yang mencolok bersih. Pola geometri keraton Kasultanan Yogyakarta sangat khas, besar-besar dan sebagian diantaranya diperkaya dengan parang dan nitik. Sementara itu, batik di Puro Pakualaman merupakan perpaduan antara pola batik Keraton Kasultanan Yogyakarta dan warna batik Keraton Surakarta.'],
            ['Batik Lasem', 'Dengan banyaknya jenis batik dari berbagai daerah di Indonesia tentunya membuat batik itu sendiri memiliki motif yang unik dan berbeda-beda. Tidak hanya itu, bahkan ada pula batik paduan antara dua budaya, yakni Jawa dan Tionghoa. Dari paduan antara dua budaya tersebut terciptalah batik lasem. Nama lasem diambil dari salah satu daerah yang terletak di pantai utara Pulau Jawa, Kabupaten Rembang, Jawa Tengah. Menurut sejarah, munculnya batik lasem melekat dengan Laksamana Cheng Ho. Daerah Lasem adalah tempat mendarat pertama kali pasukan Laksamana Cheng Ho dan juga daerah yang pertama kali kedatangan masyarakat Tionghoa.'],
            ['Batik Megamendung', 'Batik Megamendung merupakan karya seni batik yang identik dan bahkan menjadi ikon batik daerah Cirebon dan daerah Indonesia lainnya. Motif batik ini mempunyai kekhasan yang tidak ditemui di daerah penghasil batik lain. Bahkan karena hanya ada di Cirebon dan merupakan mahakarya, Departemen Kebudayaan dan Pariwisata akan mendaftarkan motif megamendung ke UNESCO untuk mendapatkan pengakuan sebagai salah satu warisan dunia. Motif megamendung sebagai motif dasar batik sudah dikenal luas sampai ke manca negara. Kekhasan motif megamendung tidak saja pada motifnya yang berupa gambar menyerupai awan dengan warna-warna tegas, tetapi juga nilai-nilai filosofi yang terkandung di dalam motifnya. Hal ini berkaitan erat dengan sejarah lahirnya batik secara keseluruhan di Cirebon'],
            ['Batik Parang', 'Batik Parang merupakan salah satu motif batik yang paling tua di Indonesia. Parang berasal dari kata Pereng yang berarti lereng. Perengan menggambarkan sebuah garis menurun dari tinggi ke rendah secara diagonal. Susunan motif S jalin-menjalin tidak terputus melambangkan kesinambungan. Bentuk dasar huruf S diambil dari ombak samudra yang menggambarkan semangat yang tidak pernah padam. Batik ini merupakan batik asli Indonesia yang sudah ada sejak zaman keraton Mataram Kartasura (Solo).'],
            ['Batik Pekalongan', 'Batik Pekalongan termasuk batik pesisiran. Dari sisi motif, sebenarnya batik Pekalongan mirip dengan batik Solo maupun Yogyakarta. Keunggulan batik Pekalongan terletak pada penggunaan warna. Sehelai kain batik bisa menggunakan delapan warna sehingga terlihat lebih indah dan menarik dibanding batik-batik dari daerah lain. Warna-warna yang digunakan antara lain gradasi merah muda, merah tua, kuning terang, jingga, coklat, biru muda, hijau muda, hijau tua, dan ungu. Batik Pekalongan menjadi sangat khas karena bertopang sepenuhnya pada ratusan pengusaha kecil, bukan pada segelintir pengusaha bermodal besar. Sejak berpuluh tahun lampau hingga sekarang, sebagian besar proses produksi batik Pekalongan dikerjakan di rumah-rumah. Akibatnya, batik Pekalongan menyatu erat dengan kehidupan masyarakat Pekalongan yang kini terbagi dalam dua wilayah administratif, yakni Kotamadya Pekalongan dan Kabupaten Pekalongan.'],
            ['Batik Priangan', 'Batik Priangan adalah istilah yang digunakan untuk memberikan identitas pada berbagai batikan yang dihasilkan dan berlangsung di Priangan, daerah di Jawa Barat dan Banten yang penduduknya berbahasa dan berbudaya Sunda. Mencakup antara lain wilayah kota dan kabupaten Cianjur, Bandung, Sumedang, Tasikmalaya, dan Ciamis. Garut, Ciamis, dan Tasikmalaya merupakan daerah-daerah di mana sisa keberadaan tradisi seni kriya batik Priangan masih terlacak. Karena batik Ciamisan dan Garutan sudah membentuk ciri khas nya sendiri, ciri khas batik Priangan masih dapat dilihat pada batik Tasikmalaya. Apabila dilihat dari segi motifnya, batik Tasikmalaya dibedakan menjadi 3 jenis, yaitu batik bermotif payung, batik bermotif flora, dan batik bermotif fauna. Bedanya dengan batik lain, motif-motif pada batik digambar secara rapi dan simetris sehingga kesan elegan muncul dari batik Tasik ini. Dari segi kerapian dan corak warna dari batik ini juga menimbulkan keindahan tersendiri. Batik Tasikmalaya memiliki warna cerah seperti merah, hijau, dan biru karena batik ini mendapat pengaruh dari batik pesisiran'],
            ['Batik Sekar', 'Batik Sekar Jagad adalah salah satu motif batik khas Indonesia. Motif ini mengandung makna kecantikan dan keindahan sehingga orang lain yang melihat akan terpesona. Ada pula yang beranggapan bahwa motif Sekar Jagad sebenarnya berasal dari kata "kar jagad" yang diambil dari bahasa Jawa (Kar=peta; Jagad=dunia), sehingga motif ini juga melambangkan keragaman di seluruh dunia.'],
            ['Batik Sidoluhur', 'Batik sidoluhur merupakan batik keraton yang berkembang di Yogyakarta maupun Surakarta. Batik ini memiliki makna keluhuran. Orang Jawa dalam menjalani kehidupannya selalu mencari keluhuran baik materi maupun non materi. Keluhuran materi biasanya ditunjukkan melalui kecukupan segala aspek ragawi. Keluhuran materi bisa didapatkan melalui usaha dan kerja keras sesuai dengan jabatan, pangkat, derajat, maupun profesinya. Sedangkan keluhuran non materi biasa ditunjukkan melalui budi, tutur, dan tindakan yang mulia.'],
            ['Batik Sidomukti', 'Motif batik sidomukti merupakan motif batik yang berasal dari Surakarta, Jawa Tengah. Motif ini merupakan perkembangan dari motif batik sidomulyo. Latar motif batik sidomulyo berwarna putih kemudian oleh Paku Buwono IV diubah dengan motif ukel yang kemudian dinamakan motif batik sidomukti. Motif batik ini merupakan salah satu jenis batik keraton yang biasanya dibuat dengan zat warna soga alam. Motif batik ini asli dan kuno atau klasik seperti aslinya. Motif batik ini biasanya digunakan pada saat upacara pernikahan. Sidomukti berasal dari Bahasa jawa yaitu dari kata “sido” yang memiliki arti jadi/menjadi/terkabul/terus-menerus dan kata “mukti” yang memiliki arti mulia, kebahagiaan, berkuasa, disegani, dan sejahtera. Sehingga motif batik sidomukti memiliki makna bahwa harapan atau keinginan untuk mencapai kebahagiaan lahir dan batin. Atau untuk pasangan yang menikah diharapkan kedua mempelai akan memiliki masa depan yang baik dan penuh kebahagiaan.'],
            ['Batik Sogan', 'Batik Sogan merupakan salah satu jenis batik bernuansa klasik. Dinamakan batik sogan karena pada awal mulanya, proses pewarnaan batik ini  menggunakan pewarna alami yang diambil dari batang kayu pohon soga. Batik Sogan klasik merupakan jenis batik yang identik dengan daerah keraton Jawa yaitu Yogyakarta dan Solo, motifnya pun biasanya mengikuti pakem motif-motif klasik keraton. Sogan Yogya dan Solo juga dapat dibedakan dari warnanya. Biasanya sogan Yogya dominan berwarna coklat tua-kehitaman dan putih, sedangkan sogan Solo berwarna coklat-oranye dan coklat. '],
            ['Batik Tambal', 'Batik tambal merupakan salah satu batik klasik yang berkembang di lingkungan keraton Yogyakarta sehingga dalam pembuatannya selalu dibubuhi doa dan harapan kepada Tuhan. Selain itu, batik ini memiliki pola khas sehingga mudah dikenali, seperti batik tambal yang terdiri dari berbagai motif yang disusun ke dalam satu kain. Motif batik tambal mempunyai guna tambal bermakna menambal atau memperbaiki hal-hal yang rusak. Dalam perjalanan hidupnya, manusia harus memperbaiki diri menuju kehidupan yang semakin adil, lahir maupun batin. Dahulu, kain batik bermotif tambal dipercaya dapat menolong kesembuhan orang yang sakit. Kegiatannya yaitu dengan menyelimuti orang sakit tersebut dengan kain motif tambal. Kepercayaan ini muncul karena orang yang sakit diasumsikan mempunyai sesuatu “yang kurang”, sehingga untuk mengobatinya perlu “ditambal”.']
        ];

        foreach($lists as $list) {
            BatikCategory::create([
                'name' => $list[0],
                'description' => $list[1]
            ]);
        }

    }
}
